---
title: "Chapter 2 - Data Visualization"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```


## Scatterplots

```{r, message=FALSE}
library(nycflights13)
library(dplyr)
library(ggplot2)
```

### Alaska Airlines Inc. flights only

```{r}
alaska_flights <- flights %>% 
  filter(carrier == 'AS')
```

### Standard Scatterplot

```{r}
ggplot(data = alaska_flights, mapping = aes(x = dep_delay, y = arr_delay)) +
  geom_point()
```


### Prevent Overplotting: Adjust Transparency of Points

```{r}
ggplot(data = alaska_flights, mapping = aes(x = dep_delay, y = arr_delay)) +
  geom_point(alpha = 0.2)
```

### Prevent Overplotting: Jittered Points

```{r}
ggplot(data = alaska_flights, mapping = aes(x = dep_delay, y = arr_delay)) +
  geom_jitter(width = 30, height = 30)
```


## Linegraphs


```{r}
glimpse(weather)
```

```{r}
early_january_weather <- weather %>% 
  filter(origin == "EWR", month == 1, day <= 15)
```

### Newark Temperature (C) in early January 2013

```{r}
ggplot(data = early_january_weather, aes(x = time_hour, y = (temp - 32) * 5/9)) +
  geom_line()
```

### Newark Temperature (C) in 2013

```{r}
jan_feb_weather <- weather %>% 
  filter(origin == "EWR", month < 3) %>% 
  mutate(temp = (temp - 32) * 5/9)

ggplot(jan_feb_weather, aes(x = time_hour, y = temp)) +
  geom_line()
```


## Histograms

```{r}
ggplot(data = weather, mapping = aes(x = temp)) +
  geom_histogram()
```

```{r}
ggplot(data = weather, mapping = aes(x = temp)) +
  geom_histogram(color = "white", breaks = seq(0, 100, 10))
```

## Facets

```{r}
ggplot(data = weather, mapping = aes(x = temp)) +
  geom_histogram(binwidth = 5, color = "white") +
  facet_wrap(~ month)
```

```{r}
ggplot(data = weather, mapping = aes(x = temp)) +
  geom_histogram(binwidth = 5, color = "white") +
  facet_wrap(~ month, nrow = 4)
```

